name: Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  release:
    types: 
      - released
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build with .NET Framework 4.6.2
        run: |
          dotnet publish --framework net462 -c Release --sc true -o build/net462 \
            -r win10-x64 src/LipUI/LipUI.csproj

      - name: Build with .NET 7.0
        run: |
          dotnet publish --framework net7.0-windows -c Release --sc true \
            -o build/net7.0-windows -r win10-x64 src/LipUI/LipUI.csproj

      - name: Pack artifacts
        run: |
          zip -9r LipUI-net462-win10-x64.zip build/net462
          zip -9r LipUI-net7.0-windows-win10-x64.zip build/net7.0-windows
            
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            LipUI-net462-win10-x64.zip
            LipUI-net7.0-win10-x64.zip