on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - runtime: win-arm64
            platform: arm64
          - runtime: win-x64
            platform: x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: |
          dotnet build src/LipUI/LipUI.csproj -c Release -o temp

          dotnet build src/LipUI/LipUI.csproj -c Release -o bin -r ${{ matrix.runtime }} `
          -p:DebugType=none -p:Platform=${{ matrix.platform }}

          copy temp/runtimes/win10-${{ matrix.platform }}`
          /native/Microsoft.WindowsAppRuntime.Bootstrap.dll bin

      - uses: actions/upload-artifact@v4
        with:
          name: LipUI-${{ matrix.runtime }}-${{ github.sha }}
          path: bin

  check-style:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet format --verify-no-changes src/LipUI
