on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build
        run: |
          dotnet publish src/LipUI.sln -c Release -o build/

      - uses: actions/upload-artifact@v3
        with:
          name: net7.0-windows-win10-x64
          path: |
            build/
