on:
  release:
    types: 
      - published

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build
        run: |
          dotnet publish src/LipUI/LipUI.csproj -c Release -f net7.0-windows -o build/ -r win10-x64 --sc true

      - uses: actions/upload-artifact@v3
        with:
          name: net7.0-windows-win10-x64
          path: |
            build/

  upload-to-release:
    needs: 
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: net7.0-windows-win10-x64
          path: artifacts/

      - name: Copy essential files
        run: |
          cp CHANGELOG.md LICENSE README.md artifacts/

      - name: Pack artifacts
        run: |
          cd artifacts
          zip -9r ../lipui-net7.0-windows-win10-x64.zip *
          cd ..

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          files: |
            lipui-net7.0-windows-win10-x64.zip
