on:
  release:
    types: 
      - published

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        framework:
          - net462
          - net7.0-windows
        runtime:
          - win10-x64
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build
        run: |
          dotnet publish src/LipUI/LipUI.csproj -c Release -f ${{ matrix.framework }} -o build/ -r ${{ matrix.runtime }} --sc true

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.framework }}-${{ matrix.runtime }}
          path: |
            build/

  upload-to-release:
    needs: 
      - build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework:
          - net462
          - net7.0-windows
        runtime:
          - win10-x64
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.framework }}-${{ matrix.runtime }}
          path: artifacts/

      - name: Copy essential files
        run: |
          cp CHANGELOG.md LICENSE README.md artifacts/

      - name: Pack artifacts
        run: |
          cd artifacts
          zip -9r ../lipui-${{ matrix.framework }}-${{ matrix.runtime }}.zip *
          cd ..

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          files: |
            lipui-${{ matrix.framework }}-${{ matrix.runtime }}.zip
