on:
  release:
    types: 
      - published

jobs:
  build:
    strategy:
      matrix:
        include:
          - runtime: win-arm64
            platform: arm64
          - runtime: win-x64
            platform: x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: |
          dotnet publish src/AutoUpdate/AutoUpdate.csproj -c Release -o bin -r ${{ matrix.runtime }}

          dotnet build src/LipUI/LipUI.csproj -c Release -o bin -r ${{ matrix.runtime }} `
          -p:DebugType=none -p:Platform=${{ matrix.platform }}

          copy runtimes/win10-${{ matrix.platform }}/native/Microsoft.WindowsAppRuntime.Bootstrap.dll bin

      - uses: actions/upload-artifact@v4
        with:
          name: LipUI-${{ matrix.runtime }}-${{ github.sha }}
          path: bin

  update-changelog:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2

      - uses: softprops/action-gh-release@v1
        with:
          body: |
            ${{ steps.extract-release-notes.outputs.release_notes }}

  upload-to-release:
    needs:
      - build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime:
          - win-arm64
          - win-x64
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: LipUI-${{ matrix.runtime }}-${{ github.sha }}
          path: bin

      - run: |
          cp CHANGELOG.md COPYING README.md bin/

      - name: Create archive
        run: |
          cd bin
          zip -r ../LipUI-${{ matrix.runtime }}.zip *
          cd ..

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            LipUI-${{ matrix.runtime }}.zip
